/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Rx_1_aliases.h>
#include <Rx_1.h>
#include <Tx_1_aliases.h>
#include <Tx_1.h>
#include <CAN_1.h>
#include <SPIM_1.h>
#include <SPIM_1_PVT.h>
#include <MOSI_aliases.h>
#include <MOSI.h>
#include <SCLK_aliases.h>
#include <SCLK.h>
#include <MISO_aliases.h>
#include <MISO.h>
#include <Timer_1.h>
#include <EEPROM_1.h>
#include <LCD_Char_1.h>
#include <SPIM_1_IntClock.h>
#include <LCD_Char_1_LCDPort_aliases.h>
#include <LCD_Char_1_LCDPort.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

